name: DevOps-exam-CI

on:
  push:
    branches: [ "master" ]

jobs:

  git_checkout_trivy_scan:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v4
    - name: File System Scan
      run: trivy fs --security-checks vuln,config --format table -o trivy-fs-report.html .


  SonarQube_analysis:

    runs-on: self-hosted
    needs: git_checkout_trivy_scan

    steps:
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      with:
        args: >
          -Dsonar.projectKey=devops-exam-app
          -Dsonar.projectName=devops-exam-app
          -Dsonar.sources=.
          -Dsonar.language=py
          -Dsonar.python.version=3
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}



  Docker_image_build:
    runs-on: self-hosted
    needs: SonarQube_analysis

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sivabalan2510/devopsexamapp:latest
          file: backend/Dockerfile
 
  Docker_scout:
    runs-on: self-hosted
    needs: Docker_image_build

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
            command: cves,recommendations,compare
            to-latest: true
            ignore-base: true
            ignore-unchanged: true
            only-fixed: true
            organization: ${{ vars.DOCKER_USERNAME }}






    
      
